version: '3.9'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    env_file:
      - ../.env
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    ports:
      - '5432:5432'